const image = (name) => ({ path: `assets/images/${name}.png`, required: true });

export const CONFIG = {
  meta: { title: 'Space Attack', version: '1.0.0', creditsPath: 'CREDITS.md' },
  arena: { width: 800, height: 600, paddingPx: 28, playerY: 535, defenseLineY: 566, enemyFloorY: 545 },
  simulation: { stepSec: 1 / 60, maxFrameSec: 0.1, maxSteps: 6, maxProjectiles: 160, maxEffects: 64 },
  controls: {
    left: ['ArrowLeft', 'KeyA'], right: ['ArrowRight', 'KeyD'], fire: ['Space'],
    confirm: ['Enter'], pause: ['KeyP', 'Escape'], mute: ['KeyM'], tuning: ['KeyT'],
  },
  player: {
    spriteId: 'player', sizePx: { width: 52, height: 40 }, hitboxInsetPx: 9,
    speedPxSec: 360, maxHealth: 100, ships: 3, fireIntervalSec: 0.18,
    projectileId: 'playerShot', respawnDelaySec: 0.8, invulnerableSec: 1.5,
    spawn: { x: 400, y: 535 }, hitInvulnerableSec: 0.65,
  },
  projectileTypes: {
    playerShot: { spriteId: 'playerLaser', sizePx: { width: 7, height: 24 }, speedPxSec: -660, damage: 1, lifetimeSec: 3, faction: 'player', hitboxInsetPx: 0 },
    enemyShot: { spriteId: 'enemyLaser', sizePx: { width: 7, height: 20 }, speedPxSec: 270, damage: 35, lifetimeSec: 4, faction: 'enemy', hitboxInsetPx: 0 },
  },
  enemyTypes: {
    scout: { spriteId: 'scout', sizePx: { width: 42, height: 34 }, hitboxInsetPx: 5, health: 1, points: 100, contactDamage: 45, escapeDamage: 15, movementId: 'formation', projectileId: 'enemyShot' },
    diver: { spriteId: 'diver', sizePx: { width: 42, height: 34 }, hitboxInsetPx: 5, health: 1, points: 150, contactDamage: 45, escapeDamage: 15, movementId: 'diver', projectileId: 'enemyShot' },
    armored: { spriteId: 'armored', sizePx: { width: 46, height: 38 }, hitboxInsetPx: 5, health: 2, points: 250, contactDamage: 55, escapeDamage: 20, movementId: 'formation', projectileId: 'enemyShot' },
  },
  waves: {
    templates: [
      { id: 'scouts', rows: [Array(8).fill('scout'), Array(8).fill('scout')], spacingPx: { x: 66, y: 56 }, origin: { x: 155, y: 70 }, formationSpeedPxSec: 35, fireIntervalSec: 1.2, diveIntervalSec: 4, maxDivers: 0 },
      { id: 'interceptors', rows: [Array(8).fill('diver'), Array(8).fill('scout'), Array(8).fill('scout')], spacingPx: { x: 66, y: 52 }, origin: { x: 155, y: 60 }, formationSpeedPxSec: 42, fireIntervalSec: 1, diveIntervalSec: 3.2, maxDivers: 1 },
      { id: 'heavy', rows: [Array(8).fill('armored'), Array(8).fill('diver'), Array(8).fill('scout')], spacingPx: { x: 66, y: 52 }, origin: { x: 155, y: 60 }, formationSpeedPxSec: 48, fireIntervalSec: 0.9, diveIntervalSec: 2.8, maxDivers: 2 },
    ],
    intermissionSec: 1.2,
    growth: { speedPerWave: 0.08, extraEnemiesPerCycle: 2, fireIntervalFactor: 0.94 },
    caps: { enemyCount: 48, speedMultiplier: 2.5, minFireIntervalSec: 0.35, minDiveIntervalSec: 0.75, maxDivers: 4 },
    diveSpeedPxSec: 190, diveSwayPx: 60, diveSwayRate: 3, rowStepPx: 16,
  },
  damage: { clearShotsOnRespawn: true, clearShotsOnWave: true },
  assets: {
    images: { player: image('player-ship'), playerRed: image('player-ship-red'), playerGreen: image('player-ship-green'), scout: image('enemy-scout'), diver: image('enemy-interceptor'), armored: image('enemy-heavy'), playerLaser: image('player-laser'), enemyLaser: image('enemy-laser'), background: image('space-background'),
      ...Object.fromEntries(Array.from({ length: 20 }, (_, i) => [`fire${i}`, image(`fire${String(i).padStart(2, '0')}`)])),
    },
    sounds: { explosion: { path: 'assets/audio/explosion.ogg', required: false }, playerShot: { path: 'assets/audio/player-shot.ogg', required: false }, enemyShot: { path: 'assets/audio/enemy-shot.ogg', required: false }, playerHit: { path: 'assets/audio/player-hit.ogg', required: false } },
    music: { title: { path: 'assets/audio/title.ogg', loop: true }, level1: { path: 'assets/audio/level-1.ogg', loop: true } },
  },
  audio: {
    masterVolume: 0.7, musicVolume: 0.35, sfxVolume: 0.6, maxConcurrentEffects: 6,
    fadeSec: 0.65, startMuted: false,
    events: { enemyDestroyed: 'explosion', playerDestroyed: 'playerHit', playerHit: 'playerHit', playerFired: 'playerShot', enemyFired: 'enemyShot' },
    tracksByScreen: { title: 'title', playing: 'level1' },
  },
  tuning: {
    storageKey: 'space-attack.settings.v1', version: 1, defaultTheme: 'deep-space',
    themes: {
      'deep-space': { label: 'Deep space', background: '#10151d', surface: '#19212c', text: '#eef4fa', muted: '#adb9c8', accent: '#82caff', ink: '#10151d', border: '#64748b', arena: '#080e18' },
      'phosphor': { label: 'Phosphor', background: '#101a16', surface: '#1b2a23', text: '#edf7ef', muted: '#afc6b6', accent: '#b1e39b', ink: '#101a16', border: '#6b8874', arena: '#07120e' },
      'solar': { label: 'Solar', background: '#201710', surface: '#2e2219', text: '#fff3df', muted: '#cfbda5', accent: '#f4c06c', ink: '#201710', border: '#95806b', arena: '#140d08' },
    },
    playerShips: [ { id: 'player', label: 'Blue pilot' }, { id: 'playerRed', label: 'Red pilot' }, { id: 'playerGreen', label: 'Green pilot' } ],
    fields: [
      { path: 'player.speedPxSec', label: 'Ship speed', min: 120, max: 700, step: 10, unit: 'px/s' },
      { path: 'player.fireIntervalSec', label: 'Shot interval', min: 0.08, max: 0.5, step: 0.01, unit: 's' },
      { path: 'waves.diveSpeedPxSec', label: 'Dive speed', min: 80, max: 350, step: 10, unit: 'px/s' },
      { path: 'waves.templates.0.formationSpeedPxSec', label: 'Opening fleet speed', min: 20, max: 180, step: 5, unit: 'px/s' },
      { path: 'waves.growth.speedPerWave', label: 'Difficulty growth', min: 0, max: 0.2, step: 0.01, unit: '/wave' },
      { path: 'audio.musicVolume', label: 'Music volume', min: 0, max: 1, step: 0.05, unit: '' },
      { path: 'audio.sfxVolume', label: 'Effects volume', min: 0, max: 1, step: 0.05, unit: '' },
    ],
    text: { title: 'Flight tuning', intro: 'Saved in this browser. Combat pauses while tuning.', close: 'Close tuning', reset: 'Reset defaults', theme: 'Theme', playerShip: 'Your ship', nextWave: 'Difficulty changes apply from the next wave.', storageError: 'Browser storage unavailable. Settings apply for this session.', resetStatus: 'Default settings restored.' },
  },
  visuals: {
    font: '"Consolas", "Courier New", monospace', maxDpr: 2, backgroundAlpha: 0.18,
    starLayers: [
      { count: 42, speedPxSec: 10, radiusPx: 1, alpha: 0.3, parallax: 0.02 },
      { count: 26, speedPxSec: 27, radiusPx: 1.5, alpha: 0.5, parallax: 0.05 },
      { count: 14, speedPxSec: 58, radiusPx: 2, alpha: 0.8, parallax: 0.1 },
    ],
    hitFlashSec: 0.1, hitFlashAlpha: 0.18, shakeSec: 0.16, shakePx: 4, shakeHz: 35,
    explosionSec: 0.55, particleCount: 18, particleSpeed: 135, particleSpread: 0.6, explosionFlashSec: 0.07,
    flameSize: { width: 14, height: 22 }, flameOffset: 23, flameFps: 24,
    blinkHz: 12, protectedAlpha: 0.45, reducedMotionAlpha: 0.65, particleSizePx: 3,
    reducedEffectSizePx: 8, intermissionFontPx: 26,
    thrusterFlicker: 0.25, thrusterHz: 18, muzzleSec: 0.07, muzzleRadiusPx: 10, muzzleAlpha: 0.85,
    scorePopupSec: 0.85, scoreRisePx: 42, scoreFontPx: 18, scoreStrokePx: 3,
    waveBannerSec: 1.1, waveBannerFontPx: 32, waveBannerHeightPx: 76, waveBannerAlpha: 0.85,
    screenFadeSec: 0.18, screenOpacity: 0.78, titleBobPx: 7, titleBobSec: 3.2,
    scanlineOpacity: 0.12, scanlineSpacingPx: 4, cabinetShadowPx: 8, titleShadowPx: 4, titleFontWeight: 900,
    css: { 'shell-width': '1020px', 'viewport-reserve': '350px', 'compact-title-size': '42px', 'compact-screen-pad': '24px', 'space-xs': '8px', 'space-sm': '12px', 'space-md': '20px', 'space-lg': '32px', 'space-xl': '48px', 'radius': '0px', 'control-height': '44px', 'font-sm': '13px', 'font-base': '16px', 'font-lg': '24px', 'title-size': 'clamp(42px, 7vw, 76px)', 'screen-pad': 'clamp(24px, 5vw, 56px)' },
  },
  ui: {
    subtitle: 'Hold the line. Clear the fleet.', edition: 'Arcade • Endless flight',
    loading: 'Preparing your ship…', loadError: 'Ship assets could not load. Check the local server and retry.', retry: 'Retry loading',
    start: 'Launch ship', title: 'Space Attack', titleBody: 'Pilot your ship through an endless enemy fleet. Keep moving, fire upward and survive the next wave.',
    paused: 'Flight paused', pauseBody: 'Take a breath. Your fleet will wait.', resume: 'Resume flight', mainMenu: 'Main menu',
    gameOver: 'Ship lost', gameOverBody: 'The fleet got through. Launch again and push a little further.', restart: 'Fly again',
    score: 'Score', health: 'Hull', ships: 'Ships', wave: 'Wave', finalScore: 'Final score', finalWave: 'Wave reached',
    pause: 'Pause', mute: 'Mute', unmute: 'Unmute', tuning: 'Tuning', credits: 'Asset credits',
    moveLabel: 'Move', fireLabel: 'Fire', pauseLabel: 'Pause', muteLabel: 'Mute', tuningLabel: 'Tune',
    controls: 'Flight controls', canvasLabel: 'Space Attack playfield. Move with arrows or A and D; Space fires.',
    intermission: 'Next wave', waveCleared: 'Fleet cleared', scorePrefix: '+', respawning: 'Deploying reserve ship', ready: 'Ready to launch',
    audioUnavailable: 'Audio unavailable. You can continue silently.',
    footer: 'Kenney artwork · Juhani Junkala audio', scoreDigits: 6,
  },
};

const dial = (path, label, min, max, step, unit, group) => ({ path, label, min, max, step, unit, group });
for (const field of CONFIG.tuning.fields) field.group = field.path.startsWith('audio.') ? 'Audio' : 'Gameplay';
CONFIG.tuning.fields.push(
  dial('audio.fadeSec', 'Music crossfade', 0, 2, 0.05, 's', 'Audio'),
  ...CONFIG.visuals.starLayers.flatMap((layer, index) => [
    dial(`visuals.starLayers.${index}.count`, `Layer ${index + 1} stars`, 0, 120, 1, '', 'Starfield'),
    dial(`visuals.starLayers.${index}.speedPxSec`, `Layer ${index + 1} speed`, 0, 150, 1, 'px/s', 'Starfield'),
    dial(`visuals.starLayers.${index}.radiusPx`, `Layer ${index + 1} size`, 0.5, 4, 0.5, 'px', 'Starfield'),
    dial(`visuals.starLayers.${index}.alpha`, `Layer ${index + 1} brightness`, 0, 1, 0.05, '', 'Starfield'),
    dial(`visuals.starLayers.${index}.parallax`, `Layer ${index + 1} parallax`, 0, 0.3, 0.01, '', 'Starfield'),
  ]),
  ...[
    ['thrusterFlicker', 'Thruster flicker', 0, 0.8, 0.05, ''],
    ['thrusterHz', 'Thruster rate', 0, 30, 1, 'Hz'],
    ['muzzleSec', 'Muzzle duration', 0, 0.15, 0.01, 's'],
    ['muzzleRadiusPx', 'Muzzle size', 0, 20, 1, 'px'],
    ['muzzleAlpha', 'Muzzle brightness', 0, 1, 0.05, ''],
    ['particleCount', 'Explosion particles', 0, 40, 1, ''],
    ['particleSpeed', 'Particle speed', 0, 300, 5, 'px/s'],
    ['particleSpread', 'Particle speed spread', 0, 1, 0.05, ''],
    ['particleSizePx', 'Particle size', 1, 6, 1, 'px'],
    ['explosionSec', 'Explosion duration', 0.1, 1.5, 0.05, 's'],
    ['explosionFlashSec', 'Explosion core flash', 0, 0.15, 0.01, 's'],
    ['hitFlashSec', 'Hit flash duration', 0, 0.15, 0.01, 's'],
    ['hitFlashAlpha', 'Hit flash intensity', 0, 0.3, 0.01, ''],
    ['shakeSec', 'Hit shake duration', 0, 0.3, 0.01, 's'],
    ['shakePx', 'Hit shake distance', 0, 8, 0.5, 'px'],
    ['shakeHz', 'Hit shake rate', 10, 60, 1, 'Hz'],
    ['scorePopupSec', 'Score popup duration', 0.1, 2, 0.05, 's'],
    ['scoreRisePx', 'Score rise distance', 0, 100, 1, 'px'],
    ['scoreFontPx', 'Score popup font', 12, 32, 1, 'px'],
    ['scoreStrokePx', 'Score outline', 0, 5, 0.5, 'px'],
  ].map(([key, ...values]) => dial(`visuals.${key}`, ...values, 'Combat feedback')),
  ...[
    ['waveBannerSec', 'Wave banner duration', 0.2, 3, 0.1, 's'],
    ['waveBannerFontPx', 'Wave banner font', 18, 48, 1, 'px'],
    ['waveBannerHeightPx', 'Wave banner height', 50, 120, 2, 'px'],
    ['waveBannerAlpha', 'Wave banner background', 0, 1, 0.05, ''],
    ['screenFadeSec', 'Screen fade', 0, 0.3, 0.01, 's'],
    ['screenOpacity', 'Menu background opacity', 0.6, 1, 0.01, ''],
    ['titleBobPx', 'Title bob distance', 0, 16, 1, 'px'],
    ['titleBobSec', 'Title bob period', 1, 8, 0.1, 's'],
    ['scanlineOpacity', 'Scanline intensity', 0, 0.25, 0.01, ''],
    ['scanlineSpacingPx', 'Scanline spacing', 2, 8, 1, 'px'],
    ['cabinetShadowPx', 'Cabinet shadow', 0, 12, 1, 'px'],
    ['titleShadowPx', 'Title shadow', 0, 8, 1, 'px'],
    ['titleFontWeight', 'Title weight', 400, 900, 100, ''],
  ].map(([key, ...values]) => dial(`visuals.${key}`, ...values, 'Arcade presentation')),
  { path: 'ui.waveCleared', label: 'Wave-clear caption', type: 'text', group: 'Arcade presentation' },
  { path: 'ui.scorePrefix', label: 'Score prefix', type: 'text', group: 'Arcade presentation' },
  { path: 'visuals.font', label: 'Arcade font stack', type: 'text', group: 'Arcade presentation' },
);
